# Generated by Django 5.0.9 on 2026-09-11 04:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('showrooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_sale', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('card_sale', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_sale', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_balances', to='showrooms.showroom')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_qty', models.PositiveIntegerField(default=0)),
                ('received_qty', models.PositiveIntegerField(default=0)),
                ('sold_qty', models.PositiveIntegerField(default=0)),
                ('return_qty', models.PositiveIntegerField(default=0)),
                ('closing_qty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_stocks', to='products.product')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_stocks', to='showrooms.showroom')),
            ],
            options={
                'ordering': ['-date', 'product__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailybalance',
            constraint=models.UniqueConstraint(fields=('showroom', 'date'), name='unique_daily_balance_entry'),
        ),
        migrations.AddConstraint(
            model_name='dailystock',
            constraint=models.UniqueConstraint(fields=('showroom', 'product', 'date'), name='unique_daily_stock_entry'),
        ),
    ]
