# Generated by Django 5.0.9 on 2026-09-13 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
        ('showrooms', '0004_remove_showroom_credentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factory_stock', to='products.product')),
            ],
            options={
                'verbose_name': 'Factory Stock',
                'verbose_name_plural': 'Factory Stock',
            },
        ),
        migrations.CreateModel(
            name='ShowroomStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showroom_stocks', to='products.product')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='showrooms.showroom')),
            ],
            options={
                'verbose_name': 'Showroom Stock',
                'verbose_name_plural': 'Showroom Stocks',
                'ordering': ['showroom', 'product'],
                'unique_together': {('showroom', 'product')},
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('receive', 'Receive from Factory'), ('sale', 'Sale to Customer'), ('return', 'Return to Factory')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers', to='products.product')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers', to='showrooms.showroom')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['showroom', 'date'], name='inventory_s_showroo_9d0d13_idx'), models.Index(fields=['product', 'date'], name='inventory_s_product_dd7cb9_idx')],
            },
        ),
    ]
