# Generated by Django 5.0.9 on 2026-09-11 15:05

from django.db import migrations, models
from django.contrib.auth.hashers import make_password


class Migration(migrations.Migration):

    dependencies = [
        ('showrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom',
            name='username',
            field=models.CharField(default='showroom_user', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showroom',
            name='password',
            field=models.CharField(default=make_password('changeme'), max_length=255),
            preserve_default=False,
        ),
    ]
